nashErr = BasicLinearRegression('Processed/New/nashville_processed');
artErr = BasicLinearRegression('Processed/New/art_processed');
redErr = BasicLinearRegression('Processed/New/redfin_processed');
kingErr = BasicLinearRegression('Processed/New/kingcounty_processed');
disp('Nashville:');
disp(nashErr);
disp('ART:');
disp(artErr);
disp('Redfin:');
disp(redErr);
disp('Kings:');
disp(kingErr);
